
import React from 'react';
import { LayoutDashboard, Zap, Shield, Network, LineChart, Cpu, Globe, Share2, Layers, Sliders, Mail, Target, BarChart3, Users, Rocket, Search, Quote, FileCode, Workflow, Milestone, Lightbulb, Trophy, CheckCircle2, SearchCode, BarChart, Eye, Sparkles, Box, FlaskConical, HeartPulse, Home, Infinity, Monitor, ShieldCheck, MapPin, Scale, UserCheck, Briefcase, Landmark, Percent, Gift, Code, Database, Microscope, Palette, Terminal, Brain, Factory, Stethoscope, Shirt, HardDrive, Bot, CircuitBoard, Radio, Component, FileJson, CloudLightning, BadgeDollarSign, FileText, ShoppingBag, Wand2, Scale3D, Boxes, GitMerge, MessageSquare, UserPlus, FileSearch, Megaphone, CheckSquare, Store, Video, Truck, Server, Container, Blocks, Handshake, Languages, Compass, TrendingUp, UserCircle, Star, Activity, ShoppingCart, PenTool, Layout, Send, Lock, HomeIcon, Image, ChevronDown, Link, MousePointer2, ScanSearch, CandlestickChart, VideoIcon, MessageCircle, MailSearch, UserCheck2, ListMusic, DatabaseZap, ImageIcon, PaletteIcon, WandSparkles, ShieldCheck as SovereigntyIcon, Server as ServerIcon, Lock as PrivateIcon, Sparkles as MarketIcon, Terminal as CodeIcon, Activity as AudioIcon, MonitorPlay as VideoPlayIcon, Binary, Newspaper, Fingerprint, BarChart4, BookOpen, BrainCircuit } from 'lucide-react';
import { ProductSystem, PricingPlan, Language, CaseStudy, AISearchTool, GeoStep, CoreValue, AffiliateBenefit, JobPosting, StrategicPartner, ToolCategory, AIModel, MCPServer } from './types';

export const SYSTEMS: ProductSystem[] = [
  { 
    id: 'strat-team', 
    title: { en: '1000+ Unified AI Matrix', zh: '千模主权矩阵' }, 
    description: { en: 'Integrated 1000+ models from OpenRouter & AI/ML API. Unified endpoint sovereignty.', zh: '集成 OpenRouter 与 AI/ML API 的 1000+ 顶尖模型。统一接口，主权隔离。' }, 
    icon: 'Cpu' 
  },
  { 
    id: 'strat-geo', 
    title: { en: 'Taiji GEO Engine', zh: '太极 GEO 营销引擎' }, 
    description: { en: 'Generative Engine Optimization (GEO). Boost citation rates in ChatGPT & Perplexity.', zh: '生成引擎优化 (GEO)。基于普林斯顿论文，提升品牌在 AI 搜索中的引用率。' }, 
    icon: 'Binary' 
  },
  { 
    id: 'tactics-growth', 
    title: { en: 'Snov.io B2B Engine', zh: 'Snov.io B2B 获客引擎' }, 
    description: { en: 'Automated lead generation and drip campaigns via Snov.io v2 API.', zh: '通过 Snov.io v2 API 实现全自动获客与冷邮序列外联。' }, 
    icon: 'MailSearch' 
  },
  { 
    id: 'tactics-channel', 
    title: { en: 'Omni-Channel Reach', zh: '全球全渠道触达' }, 
    description: { en: 'Connect TikTok viral traffic via AlphaVantage trend prediction.', zh: '利用 AlphaVantage 趋势预测，精准对接 TikTok 爆款流量。' }, 
    icon: 'Globe' 
  },
  { 
    id: 'strat-capital', 
    title: { en: 'Smart Finance Core', zh: '智能财务核心' }, 
    description: { en: 'Real-time profit tracking & Lemon Squeezy payment nodes.', zh: '实时追踪利润与现金流，支持 Lemon Squeezy 支付自动化。' }, 
    icon: 'Landmark' 
  },
];

export const PRICING: PricingPlan[] = [
  { id: 'hero', name: { en: 'Hero', zh: '英雄版' }, price: '$0', features: { en: ['1000+ Models', 'Basic GEO'], zh: ['1000+ 模型', '基础 GEO'] } },
  { id: 'pro', name: { en: 'Professional', zh: '专业版' }, price: '$99', features: { en: ['Priority API', 'Full GEO Lab'], zh: ['优先 API', '完整 GEO 实验室'] }, isPopular: true },
];

export const CASE_STUDIES: CaseStudy[] = [
  { id: '1', title: { en: 'Solar Inverter B2B', zh: '光伏逆变器 B2B' }, metric: '+115% Citation', image: '' },
];

export const AI_SEARCH_TOOLS: AISearchTool[] = [
  { id: 'chatgpt', name: 'ChatGPT Search', logo: '' },
  { id: 'perplexity', name: 'Perplexity', logo: '' },
];

export const GEO_IMPLEMENTATION_STEPS: GeoStep[] = [
  { id: 1, title: { en: 'Analyze', zh: '分析' }, desc: { en: 'Current visibility score', zh: '当前可见度评分' } },
];

export const CORE_VALUES: CoreValue[] = [
  { id: 'sovereignty', title: { en: 'Sovereignty', zh: '主权' }, desc: { en: 'Data ownership', zh: '数据所有权' }, icon: 'ShieldCheck' },
];

export const JOB_POSTINGS: JobPosting[] = [
  { id: '1', title: { en: 'AI Engineer', zh: 'AI 工程师' }, department: 'R&D', requirements: { en: [], zh: [] }, benefits: { en: [], zh: [] } },
];

export const LIGE_FIVE_STEPS = [
  { id: 'who', label: { en: 'WHO', zh: '定义受众' } },
];

export const GARY_WORKFLOWS = [
  { id: 'leadgen', label: { en: 'Lead Gen', zh: '获客序列' } },
];

export const TECH_STACK = [
  { name: 'Gemini 3', icon: 'Brain' },
];

export const STRATEGIC_PARTNERS: StrategicPartner[] = [
  { id: 'google', name: 'Google Cloud', logo: '' },
];

export const TOOL_CATEGORIES: ToolCategory[] = [
  { id: 'marketing', name: { en: 'Marketing', zh: '营销' }, icon: 'Zap' },
];

export const AI_MODELS: AIModel[] = [
  { id: 'gemini-3-flash', name: 'Gemini 3 Flash', provider: 'Google', category: 'Text', isFree: true },
];

export const GEO_BENEFITS = [
  { title: { en: 'Visibility', zh: '可见度' } },
];

export const MCP_SERVERS: MCPServer[] = [
  { id: 'browser-auto', name: 'Browser Automation', category: 'Browser', description: { en: 'Automate tasks', zh: '自动化任务' }, icon: 'Monitor', capabilities: ['DOM Access'] },
];

export const UI_STRINGS = {
  en: {
    website: 'Your BP',
    userHub: 'Your Hub',
    admin: 'Command Center',
    geoStudio: 'Creation Studio',
    dashboard: 'Your Growth',
    apiStudio: 'Logic Studio',
    taijiGeo: 'Taiji GEO',
    mcpMarket: 'MCP Market',
    modelMarket: 'Model Market',
    snovCenter: 'Snov.io B2B',
    bextCenter: 'BextAI Visual',
    sovereigntyCenter: 'Data Sovereignty',
    knowledgeBase: 'Knowledge Base',
    neuralTraining: 'Neural Training',
    finance: 'Financial Core',
    settings: 'Preferences',
    signIn: 'Welcome Back',
    signUp: 'Start Winning',
    signOut: 'Sign Out',
    email: 'Email',
    mobile: 'Mobile',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    sendCode: 'Send Code',
    verifyCode: 'Code',
    noAccount: "New Hero?",
    hasAccount: 'Returning Hero?',
    authTitle: 'Step into Sovereignty',
    authSub: 'You are the Hero. Simiai OS is your Tool. Manage your AI-Native empire.',
    hero: 'Super Individual',
    seed: 'Empire Builder',
    welcome: 'Welcome, Sovereign.',
    osRunning: 'Your AI Matrix is active. Master your market.',
    uploadKnowledge: 'Import Vision PDF',
    newWorkflow: 'New Growth Cycle',
    revenueGrowth: 'Efficiency & Impact Score',
    recentWorkflows: 'Active AI Nodes',
    viewAll: 'Case Studies',
    taijiTitle: 'Strategic Engine',
    taijiSub: 'Taiji GEO + Lige Logic. You define, we execute.',
    saveDraft: 'Save Progress',
    publishStudio: 'Deploy Empire',
    studioToolbox: 'Mastery Tools',
    livePreview: 'Real-time Reality',
    visibility: 'AI Citation Rate',
    optimizing: 'Scaling Your Vision...',
    apiTitle: 'Universal AI Brain',
    apiSub: '1000+ Models connected via Simiai Gateway.',
    beta: 'ULTIMATE',
    activeModel: 'Model Unit:',
    chatPlaceholder: 'Simiai: "Which model shall we use to win today?"',
    chatSub: 'Query about 1000+ models from OpenRouter & AI/ML API.',
    typeInstruction: 'Your Command...',
    launch: 'Become Unstoppable',
    docs: 'Builder Guides',
    privacy: 'Privacy Rights',
    terms: 'Sovereign Terms',
    contact: 'Hero Support',
    mission: 'Empowering every entrepreneur to become the most powerful version of themselves.',
    adminRestricted: 'Master Command',
    placeholderUrl: 'Paste your vision or PDF URL...',
    calcScore: 'Measure Success Index',
    scoreResult: 'Your Sovereignty Score',
    flexiblePlans: 'Invest in Your Evolution',
    heroText: 'Master Your Story.',
    heroSub: 'Integrated 1000+ AI Models, Snov.io & BextAI. Stop managing keys; start ruling your own empire.',
    eightPillars: 'The Eight Pillars',
    eightPillarsSub: 'From Vision to Global Retail Reality.',
    marketStats: 'The $4T Opportunity',
    marketSub: 'AI-driven commerce is shifting. Claim your 20% share of AI search traffic.',
    ligeStep: 'Methodology',
    garyWorkflow: 'Execution Hub',
    step1: 'Define WHO',
    step2: 'Perfect TOUCH',
    step3: 'Launch REACH',
    step4: 'Secure HOOK',
    step5: 'Claim SHELF',
    adPerformance: 'Visibility Metrics',
    roas: 'ROI Impact',
    spend: 'Investment',
    clicks: 'Hits',
    citationRate: 'AI Authority',
    referenceRate: 'Growth Volume',
    geoScore: 'Mastery Score',
    insights: 'Global Intel',
    insightsSub: 'Benchmarks for your unstoppable evolution.',
    caseStudies: 'Heroes Like You',
    aiComparison: 'Search Dominance',
    formula: 'Success Formula',
    formulaText: 'You + Simiai OS = Unstoppable',
    share: 'Market Share',
    advantage: 'The Edge',
    suitability: 'Persona Fit',
    traffic: 'Momentum',
    roadmap: 'Growth Roadmap',
    roadmapSub: '30 Days from Zero to Sovereignty.',
    fashionFocus: 'Fashion Hero',
    fashionFocusSub: 'Lookbooks to hooks.',
    beautyFocus: 'Beauty Architect',
    beautyFocusSub: 'Influencers to shelves.',
    medicalFocus: 'Trust Builder',
    medicalFocusSub: 'Compliance at scale.',
    affiliateTitle: 'Growth Alliance',
    affiliateSub: '10,000 partners win together.',
    investorTitle: 'Strategic Equity',
    investorSub: '¥100M raise for a ¥200M empire. Join us.',
    affiliateLink: 'Your Node',
    affiliateStats: 'Earnings',
    recruitmentTitle: 'Join Core Team',
    recruitmentSub: 'Building for 10k stores and 10M heroes.',
    recruitmentHero: 'Build for Heroes',
    jobRequirements: 'Standards',
    jobBenefits: 'Rewards',
    applyNow: 'Join Us',
    ecoSectionTitle: 'The Growth Loop',
    ecoSectionSub: 'From viral TikTok clips to supermarket checkout lanes.',
    atomicSectionTitle: 'Atomic Website',
    atomicSectionSub: '+$1 to own a high-conversion GEO-native brand site.',
    atomicOneClick: 'Deploy Now',
    partnerRecruitment: '10,000 Allies',
    strategicPartners: 'Our Alliances',
    partnersSub: 'Top associations backing your global sovereignty.',
    becomePartner: 'Join Alliance',
    applyAccess: 'Apply Access',
    browseTools: 'Browse Tools',
    toolsHeroTitle: 'Empower Your Heroic Journey',
    toolsHeroSub: 'Discover AI tools built to amplify your cross-border dominance. You rule the business; we sharpen the blade.',
    allCategories: 'All Categories',
    viewAllTools: 'View All',
    referralTitle: 'Unlock Premium Access for FREE!',
    referralSub: 'Share Simiai OS with friends and rule together.',
    referralPro: 'Invite 2 friends to Professional Plan -> Get 1 Year Premium FREE.',
    referralSme: 'Invite 2 friends to SME Plan -> Get 1 Year Functionality FREE.',
    copyReferral: 'Copy Referral Link',
    joinNow: 'Try Now',
    freeReport: 'Get Free Report',
    geoShowcaseTitle: 'Master AI Search Traffic',
    geoShowcaseSub: 'Turn your brand into the preferred reference for global AI with Taiji GEO.',
    mcpHeroTitle: 'The AI Interconnect (MCP.so)',
    mcpHeroSub: 'Connect your AI agents to the real world. 17,223+ MCP servers for browser automation, finance, and creative video production.',
    osAssistant: 'OS Assistant',
    assistantSub: 'Chat with your toolset. Natural language execution.',
    snovHeroTitle: 'Snov.io B2B Lead Hub',
    snovHeroSub: 'Accelerate your global client acquisition by 10x via official Snov.io v2 API.',
    bextHeroTitle: 'BextAI Visual Studio',
    bextHeroSub: '20x faster product visualization. Official BextAI integration for pro photography and detail pages.',
    sovereigntyHeroTitle: 'Absolute Data Sovereignty',
    sovereigntyHeroSub: 'Row-Level isolation & Zero-Knowledge architecture. Your business secrets remain yours.',
    marketHeroTitle: 'Unified Model Market',
    marketHeroSub: '1000+ Models from OpenRouter & AI/ML API. One API key to rule them all with sovereign isolation.',
    taijiGeoHeroTitle: 'Taiji GEO Optimization',
    taijiGeoHeroSub: 'Generative Engine Optimization based on Princeton research. Boost your AI citation rates by up to 115%.',
    titles: {
      public: 'Simiai OS | Empowering the Individual Hero',
      partners: 'Strategic Partners | Simiai OS',
      tools: 'Hero Tools | Simiai OS',
      auth: 'Sovereign Entry | Simiai OS',
      dashboard: 'Growth Hub | Simiai OS',
      studio: 'Creation Studio | Simiai OS',
      api: 'Logic Studio | Simiai OS',
      admin: 'Master Command | Simiai OS',
      insights: 'Global Intel | Simiai OS',
      careers: 'Join Core | Simiai OS',
      mcp: 'MCP.so Market | Simiai OS',
      assistant: 'SIMIAI OS Assistant | Simiai OS',
      snov: 'Snov.io B2B Hub | Simiai OS',
      bext: 'BextAI Visual Studio | Simiai OS',
      sovereignty: 'Data Sovereignty | Simiai OS',
      market: '1000+ Model Market | Simiai OS',
      geo: 'Taiji GEO System | Simiai OS',
      knowledge: 'Knowledge Hub | Simiai OS',
      training: 'Neural Tuning | Simiai OS'
    }
  },
  zh: {
    website: '你的 BP',
    userHub: '你的中心',
    admin: '统领中心',
    geoStudio: '创作工作室',
    dashboard: '你的成长',
    apiStudio: '逻辑实验室',
    taijiGeo: '太极 GEO',
    mcpMarket: 'MCP 市场',
    modelMarket: '模型市场',
    snovCenter: 'Snov.io 获客',
    bextCenter: '飞象AI生图',
    sovereigntyCenter: '数据主权',
    knowledgeBase: '行业知识库',
    neuralTraining: '神经网络训练',
    finance: '财务核心',
    settings: '系统偏好',
    signIn: '欢迎回来',
    signUp: '开启旅程',
    signOut: '退出系统',
    email: '邮箱地址',
    mobile: '手机号码',
    password: '密码',
    confirmPassword: '确认密码',
    sendCode: '获取验证码',
    verifyCode: '验证码',
    noAccount: '新英雄？',
    hasAccount: '回归英雄？',
    authTitle: '步入主权之路',
    authSub: '你是英雄，Simiai OS 是你的工具。管理你的 AI 原生帝国。',
    hero: '超级个体',
    seed: '帝国构建者',
    welcome: '欢迎回来，主宰者。',
    osRunning: 'AI 矩阵已就绪。开始主宰你的市场。',
    uploadKnowledge: '导入愿景 PDF',
    newWorkflow: '开启增长周期',
    revenueGrowth: '效率与影响力评分',
    recentWorkflows: '活跃 AI 节点',
    viewAll: '成功案例',
    taijiTitle: '战略引擎',
    taijiSub: '太极 GEO + 力哥逻辑。由你定义，AI 执行。',
    saveDraft: '保存进度',
    publishStudio: '部署帝国',
    studioToolbox: '掌控工具',
    livePreview: '实时现实',
    visibility: 'AI 引用率',
    optimizing: '扩展愿景中...',
    apiTitle: '全球通用大脑',
    apiSub: '通过 Simiai 网关连接 1000+ 顶尖 AI 模型。',
    beta: '终极版',
    activeModel: '大脑单元:',
    chatPlaceholder: 'Simiai: “今天我们要用哪种模型来赢？”',
    chatSub: '询问关于 OpenRouter 与 AI/ML API 的 1000+ 模型。',
    typeInstruction: '你的指令...',
    launch: '变得不可阻挡',
    docs: '构建者指南',
    privacy: '隐私权利',
    terms: '主权条款',
    contact: '英雄支持',
    mission: '赋能每一位创业者成为最强大的自己。',
    adminRestricted: '主控室',
    placeholderUrl: '粘贴你的愿景或 PDF 链接...',
    calcScore: '衡量成功指数',
    scoreResult: '你的主权评分',
    flexiblePlans: '为你的进化投资',
    heroText: '主导你的故事。',
    heroSub: '深度集成全球 1000+ AI 模型 API、Snov.io 与 飞象AI。无需管理密钥，开始主宰你的帝国。',
    eightPillars: '“八化”支柱',
    eightPillarsSub: '从商业愿景到全球零售现实。',
    marketStats: '4 万亿美元机遇',
    marketSub: 'AI 驱动商业大迁徙。占领 20% 的 AI 搜索流量份额。',
    ligeStep: '方法论',
    garyWorkflow: '执行中心',
    step1: '定义 WHO',
    step2: '完美 TOUCH',
    step3: '发布 REACH',
    step4: '掌控 HOOK',
    step5: '占领 SHELF',
    adPerformance: '可见度指标',
    roas: 'ROI 影响力',
    spend: '投入金额',
    clicks: '点击量',
    citationRate: 'AI 权威度',
    referenceRate: '增长覆盖',
    geoScore: '掌控评分',
    insights: '全球情报',
    insightsSub: '助力你不可阻挡进化的基准分析。',
    caseStudies: '像你一样的英雄',
    aiComparison: '搜索统治力',
    formula: '成功公式',
    formulaText: '你 + Simiai OS = 不可阻挡',
    share: '市场份额',
    advantage: '核心优势',
    suitability: '角色匹配',
    traffic: '增长势能',
    roadmap: '增长路线图',
    roadmapSub: '30 天，从零到主权统治。',
    fashionFocus: '时尚英雄',
    fashionFocusSub: '画册转钩子。',
    beautyFocus: '美妆架构师',
    beautyFocusSub: '达人连货架。',
    medicalFocus: '信任构建者',
    medicalFocusSub: '规模化合规。',
    affiliateTitle: '增长联盟',
    affiliateSub: '10,000 名伙伴共同赢取未来。',
    investorTitle: '战略股权',
    investorSub: '1 亿融资助力 2 亿估值帝国。加入我们。',
    affiliateLink: '你的节点',
    affiliateStats: '累计收益',
    recruitmentTitle: '加入核心团队',
    recruitmentSub: '为万家商超和千万英雄打造工具。',
    recruitmentHero: '为英雄构建',
    jobRequirements: '专业标准',
    jobBenefits: '英雄待遇',
    applyNow: '加入我们',
    ecoSectionTitle: '增长闭环',
    ecoSectionSub: '从 TikTok 爆款视频到线下商超收银台。',
    atomicSectionTitle: '原子官网',
    atomicSectionSub: '只需 +1 美元，即可拥有高转化 GEO 原生品牌站。',
    atomicOneClick: '部署部署',
    partnerRecruitment: '10,000 名盟友',
    strategicPartners: '战略同盟',
    partnersSub: '全球顶级协会，为你的全球主权背书。',
    becomePartner: '加入同盟',
    applyAccess: '获取权限',
    browseTools: '工具目录',
    toolsHeroTitle: '英雄工具库',
    toolsHeroSub: '发现旨在提升出海效率与竞争力的 AI 工具。你是生意的主宰，我们是你的最强锋刃。',
    allCategories: '所有类别',
    viewAllTools: '查看全部',
    referralTitle: '免费解锁一年高级访问！',
    referralSub: '与英雄朋友分享 Simiai OS，共同主宰全球。',
    referralPro: '推荐 2 位朋友加入专业计划 -> 获一年高级访问。',
    referralSme: '推荐 2 位朋友加入中小企业计划 -> 获一年功能免费。',
    copyReferral: '复制推荐链接',
    joinNow: '现在试试',
    freeReport: '获取免费报告',
    geoShowcaseTitle: '主宰 AI 搜索流量',
    geoShowcaseSub: '利用太极 GEO 引擎，让您的品牌成为全球 AI 的首选引用来源。',
    mcpHeroTitle: 'AI 万物互联 (MCP.so)',
    mcpHeroSub: '将您的 AI 代理连接到现实世界。17,223+ MCP 服务器提供浏览器自动化、金融分析和视频创意生成能力。',
    osAssistant: 'SIMIAI OS 助手',
    assistantSub: '自然语言调用所有 AI 工具，像聊天一样经营。',
    snovHeroTitle: 'Snov.io 获客中心',
    snovHeroSub: '让你的全球客户获取效率提升 10 倍。深度集成 Snov.io v2 API，支持域名搜索及全自动冷邮序列。',
    bextHeroTitle: '飞象AI生图中心',
    bextHeroSub: '视觉营销效率提升 20 倍。深度集成 BextAI（飞象AI）生图智能体，一键生成产品大片与详情页。',
    sovereigntyHeroTitle: '绝对数据主权',
    sovereigntyHeroSub: '后台启用多租户隔离系统。数据库、存储、计算全方位私有化，你的商业情报 100% 归你。',
    marketHeroTitle: '统一模型市场',
    marketHeroSub: '集成 1000+ 来自 OpenRouter 与 AI/ML API 的模型。一个主权 Key 掌控全球 AI 智慧。',
    taijiGeoHeroTitle: '太极 GEO 内容营销',
    taijiGeoHeroSub: '基于普林斯顿大学前沿研究。优化内容以在 ChatGPT Search/Perplexity 等 AI 引擎中获得爆表引用率。',
    titles: {
      public: 'Simiai OS | 赋能每一个商业英雄',
      partners: '战略同盟 | Simiai OS',
      tools: '英雄工具库 | Simiai OS',
      auth: '主权之门 | Simiai OS',
      dashboard: '成长中心 | Simiai OS',
      studio: '创作工作室 | Simiai OS',
      api: '逻辑实验室 | Simiai OS',
      admin: '主控室 | Simiai OS',
      insights: '全球情报 | Simiai OS',
      careers: '加入核心团队 | Simiai OS',
      mcp: 'MCP.so 市场 | Simiai OS',
      assistant: 'SIMIAI OS 助手 | Simiai OS',
      snov: 'Snov.io 获客中心 | Simiai OS',
      bext: '飞象AI视觉中心 | Simiai OS',
      sovereignty: '数据主权中心 | Simiai OS',
      market: '1000+ 模型市场 | Simiai OS',
      geo: '太极 GEO 系统 | Simiai OS',
      knowledge: '行业知识库 | Simiai OS',
      training: '神经网络训练 | Simiai OS'
    }
  }
};

export const ICON_MAP: Record<string, React.ReactNode> = {
  Zap: <Zap className="w-6 h-6" />,
  Layers: <Layers className="w-6 h-6" />,
  Shield: <Shield className="w-6 h-6" />,
  Network: <Network className="w-6 h-6" />,
  LineChart: <LineChart className="w-6 h-6" />,
  Cpu: <Cpu className="w-6 h-6" />,
  Globe: <Globe className="w-6 h-6" />,
  Share2: <Share2 className="w-6 h-6" />,
  Dashboard: <LayoutDashboard className="w-6 h-6" />,
  Sliders: <Sliders className="w-6 h-6" />,
  Mail: <Mail className="w-6 h-6" />,
  Target: <Target className="w-6 h-6" />,
  BarChart: <BarChart3 className="w-6 h-6" />,
  Users: <Users className="w-6 h-6" />,
  Rocket: <Rocket className="w-6 h-6" />,
  Search: <Search className="w-6 h-6" />,
  Quote: <Quote className="w-6 h-6" />,
  FileCode: <FileCode className="w-6 h-6" />,
  Workflow: <Workflow className="w-6 h-6" />,
  Milestone: <Milestone className="w-6 h-6" />,
  Lightbulb: <Lightbulb className="w-6 h-6" />,
  TrendingUp: <TrendingUp className="w-6 h-6" />,
  Trophy: <Trophy className="w-6 h-6" />,
  Check: <CheckCircle2 className="w-6 h-6" />,
  Audit: <SearchCode className="w-6 h-6" />,
  Analytics: <BarChart className="w-6 h-6" />,
  Preview: <Eye className="w-6 h-6" />,
  Beauty: <Sparkles className="w-6 h-6" />,
  Fashion: <Shirt className="w-6 h-6" />,
  Labs: <FlaskConical className="w-6 h-6" />,
  Medical: <HeartPulse className="w-6 h-6" />,
  Infinity: <Infinity className="w-6 h-6" />,
  Monitor: <Monitor className="w-6 h-6" />,
  ShieldCheck: <ShieldCheck className="w-6 h-6" />,
  MapPin: <MapPin className="w-6 h-6" />,
  Scale: <Scale className="w-6 h-6" />,
  UserCheck: <UserCheck className="w-6 h-6" />,
  Briefcase: <Briefcase className="w-6 h-6" />,
  Landmark: <Landmark className="w-6 h-6" />,
  Gift: <Gift className="w-6 h-6" />,
  Percent: <Percent className="w-6 h-6" />,
  Code: <Code className="w-6 h-6" />,
  Microscope: <Microscope className="w-6 h-6" />,
  Palette: <Palette className="w-6 h-6" />,
  Terminal: <Terminal className="w-6 h-6" />,
  Brain: <Brain className="w-6 h-6" />,
  Factory: <Factory className="w-6 h-6" />,
  MedicalPlus: <Stethoscope className="w-6 h-6" />,
  HardDrive: <HardDrive className="w-6 h-6" />,
  Bot: <Bot className="w-6 h-6" />,
  CircuitBoard: <CircuitBoard className="w-6 h-6" />,
  Radio: <Radio className="w-6 h-6" />,
  Component: <Component className="w-6 h-6" />,
  FileJson: <FileJson className="w-6 h-6" />,
  CloudLightning: <CloudLightning className="w-6 h-6" />,
  FileText: <FileText className="w-6 h-6" />,
  ShoppingBag: <ShoppingBag className="w-6 h-6" />,
  Wand2: <Wand2 className="w-6 h-6" />,
  Boxes: <Boxes className="w-6 h-6" />,
  GitMerge: <GitMerge className="w-6 h-6" />,
  MessageSquare: <MessageSquare className="w-6 h-6" />,
  UserPlus: <UserPlus className="w-6 h-6" />,
  FileSearch: <FileSearch className="w-6 h-6" />,
  Megaphone: <Megaphone className="w-6 h-6" />,
  CheckSquare: <CheckSquare className="w-6 h-6" />,
  Store: <Store className="w-6 h-6" />,
  Video: <Video className="w-6 h-6" />,
  Truck: <Truck className="w-6 h-6" />,
  Server: <Server className="w-6 h-6" />,
  Container: <Container className="w-6 h-6" />,
  Blocks: <Blocks className="w-6 h-6" />,
  Handshake: <Handshake className="w-6 h-6" />,
  Languages: <Languages className="w-6 h-6" />,
  Compass: <Compass className="w-6 h-6" />,
  UserCircle: <UserCircle className="w-6 h-6" />,
  Star: <Star className="w-6 h-6" />,
  Activity: <Activity className="w-6 h-6" />,
  ShoppingCart: <ShoppingCart className="w-6 h-6" />,
  PenTool: <PenTool className="w-6 h-6" />,
  Layout: <Layout className="w-6 h-6" />,
  Send: <Send className="w-6 h-6" />,
  Box: <Box className="w-6 h-6" />,
  Lock: <Lock className="w-6 h-6" />,
  HomeIcon: <HomeIcon className="w-6 h-6" />,
  Image: <Image className="w-6 h-6" />,
  ChevronDown: <ChevronDown className="w-6 h-6" />,
  MousePointer2: <MousePointer2 className="w-6 h-6" />,
  Link: <Link className="w-6 h-6" />,
  ScanSearch: <ScanSearch className="w-6 h-6" />,
  CandlestickChart: <CandlestickChart className="w-6 h-6" />,
  VideoIcon: <VideoIcon className="w-6 h-6" />,
  MessageCircle: <MessageCircle className="w-6 h-6" />,
  MailSearch: <MailSearch className="w-6 h-6" />,
  UserCheck2: <UserCheck2 className="w-6 h-6" />,
  ListMusic: <ListMusic className="w-6 h-6" />,
  DatabaseZap: <DatabaseZap className="w-6 h-6" />,
  ImageIcon: <ImageIcon className="w-6 h-6" />,
  PaletteIcon: <PaletteIcon className="w-6 h-6" />,
  WandSparkles: <WandSparkles className="w-6 h-6" />,
  Text: <FileText className="w-6 h-6" />,
  CodeMarket: <CodeIcon className="w-6 h-6" />,
  AudioMarket: <AudioIcon className="w-6 h-6" />,
  VideoMarket: <VideoPlayIcon className="w-6 h-6" />,
  Binary: <Binary className="w-6 h-6" />,
  Newspaper: <Newspaper className="w-6 h-6" />,
  Fingerprint: <Fingerprint className="w-6 h-6" />,
  BarChart4: <BarChart4 className="w-6 h-6" />,
  BookOpen: <BookOpen className="w-6 h-6" />,
  BrainCircuit: <BrainCircuit className="w-6 h-6" />,
};
